export const FETCH_ALL_BLOGS= "FETCH_ALL_BLOGS"
export const DELETE_BLOG= "DELETE_BLOG"
export const FETCH_BLOG_BY_ID= "FETCH_BLOG_BY_ID"
export const CREATE_BLOG= "CREATE_BLOG"
export const UPLOAD_IMAGE= "UPLOAD_IMAGE"
// export const = ""